version: '2'

services:
  front:
    build: ./front
    volumes:
      - ./front:/app:delegated
    ports:
      - "8080:8080"
    links:
      - api
  api:
    build: ./api
    volumes:
      - ./api:/app:delegated
    ports:
      - '3000:3000'
    expose:
      - '3000'
