
front:
  build: ./front
  volumes:
    - ./front:/app
  ports:
    - "8080:8080"
  links:
    - api

api:
  build: ./api
  volumes:
    - ./api:/app
  ports:
    - '3000:3000'
  expose:
    - '3000'
